// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSZBJ7Xh1_h8NNivkB9jiK8tHqjT03MkY',
    appId: '1:584011910016:android:bab9f17d75f2bc37588f65',
    messagingSenderId: '584011910016',
    projectId: 'login-signup-app-6de15',
    storageBucket: 'login-signup-app-6de15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDpWTbVL6YsNgNs9H_lC2srvONsXsqmUc',
    appId: '1:584011910016:ios:58c47e87613e500f588f65',
    messagingSenderId: '584011910016',
    projectId: 'login-signup-app-6de15',
    storageBucket: 'login-signup-app-6de15.appspot.com',
    iosClientId: '584011910016-jjmt3t4ee79cs0ef86596rpdnvmg4sbe.apps.googleusercontent.com',
    iosBundleId: 'com.app.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDpWTbVL6YsNgNs9H_lC2srvONsXsqmUc',
    appId: '1:584011910016:ios:58c47e87613e500f588f65',
    messagingSenderId: '584011910016',
    projectId: 'login-signup-app-6de15',
    storageBucket: 'login-signup-app-6de15.appspot.com',
    iosClientId: '584011910016-jjmt3t4ee79cs0ef86596rpdnvmg4sbe.apps.googleusercontent.com',
    iosBundleId: 'com.app.loginSignup',
  );
}
